"""
Seed Prompt Data Models

This module defines the data structures for seed prompts generated by the teacher model.
"""

from typing import Dict, List, Optional, Any, Literal
from pydantic import BaseModel, Field
from datetime import datetime
from uuid import uuid4


class PromptMetadata(BaseModel):
    """Metadata about a generated seed prompt."""
    tool_name: str = Field(..., description="Name of the target tool")
    tool_coverage: List[str] = Field(
        default_factory=list,
        description="List of parameters covered in the prompt"
    )
    complexity: Literal["simple", "medium", "complex"] = Field(
        default="medium",
        description="Complexity level of the prompt"
    )
    is_edge_case: bool = Field(
        default=False,
        description="Whether this is an edge case prompt"
    )
    edge_case_type: Optional[str] = Field(
        default=None,
        description="Type of edge case if applicable"
    )
    template_id: Optional[str] = Field(
        default=None,
        description="ID of the template used to generate this prompt"
    )
    temperature: float = Field(
        default=0.9,
        description="Temperature used during generation"
    )
    generation_timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When the prompt was generated"
    )


class ExpectedEntities(BaseModel):
    """Expected entities that should be extracted from the prompt."""
    entities: Dict[str, Any] = Field(
        default_factory=dict,
        description="Mapping of parameter names to expected values"
    )

    def has_entity(self, param_name: str) -> bool:
        """Check if an entity exists for a parameter."""
        return param_name in self.entities

    def get_entity(self, param_name: str) -> Optional[Any]:
        """Get the expected value for a parameter."""
        return self.entities.get(param_name)


class SeedPrompt(BaseModel):
    """A single seed prompt for training data generation."""
    id: str = Field(
        default_factory=lambda: f"seed_{uuid4().hex[:12]}",
        description="Unique identifier for the seed prompt"
    )
    prompt: str = Field(..., description="The user prompt text")
    expected_entities: ExpectedEntities = Field(
        default_factory=ExpectedEntities,
        description="Expected entities to extract"
    )
    metadata: PromptMetadata = Field(..., description="Prompt metadata")

    # Quality indicators
    is_valid: bool = Field(
        default=True,
        description="Whether the prompt passed validation"
    )
    validation_errors: List[str] = Field(
        default_factory=list,
        description="List of validation errors if any"
    )

    # Scoring
    quality_score: Optional[float] = Field(
        default=None,
        description="Quality score from validation (0.0-1.0)"
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }

    def to_training_format(self) -> Dict[str, Any]:
        """Convert to the format expected by the training pipeline."""
        return {
            "id": self.id,
            "prompt": self.prompt,
            "expected_entities": self.expected_entities.entities,
            "tool_name": self.metadata.tool_name,
            "complexity": self.metadata.complexity,
            "is_edge_case": self.metadata.is_edge_case,
            "quality_score": self.quality_score
        }


class SeedBatch(BaseModel):
    """A batch of seed prompts."""
    batch_id: str = Field(
        default_factory=lambda: f"batch_{uuid4().hex[:8]}",
        description="Unique batch identifier"
    )
    prompts: List[SeedPrompt] = Field(
        default_factory=list,
        description="List of seed prompts in this batch"
    )
    generation_config: Dict[str, Any] = Field(
        default_factory=dict,
        description="Configuration used to generate this batch"
    )
    created_at: datetime = Field(
        default_factory=datetime.now,
        description="Batch creation timestamp"
    )

    @property
    def total_count(self) -> int:
        """Total number of prompts in the batch."""
        return len(self.prompts)

    @property
    def valid_count(self) -> int:
        """Number of valid prompts in the batch."""
        return sum(1 for p in self.prompts if p.is_valid)

    @property
    def tool_distribution(self) -> Dict[str, int]:
        """Distribution of prompts across tools."""
        dist: Dict[str, int] = {}
        for prompt in self.prompts:
            tool = prompt.metadata.tool_name
            dist[tool] = dist.get(tool, 0) + 1
        return dist

    @property
    def complexity_distribution(self) -> Dict[str, int]:
        """Distribution of prompts across complexity levels."""
        dist: Dict[str, int] = {}
        for prompt in self.prompts:
            complexity = prompt.metadata.complexity
            dist[complexity] = dist.get(complexity, 0) + 1
        return dist

    def get_prompts_by_tool(self, tool_name: str) -> List[SeedPrompt]:
        """Get all prompts for a specific tool."""
        return [p for p in self.prompts if p.metadata.tool_name == tool_name]

    def get_valid_prompts(self) -> List[SeedPrompt]:
        """Get only valid prompts."""
        return [p for p in self.prompts if p.is_valid]

    def get_edge_cases(self) -> List[SeedPrompt]:
        """Get all edge case prompts."""
        return [p for p in self.prompts if p.metadata.is_edge_case]

    def to_jsonl(self) -> str:
        """Export batch to JSONL format for training."""
        import json
        lines = []
        for prompt in self.prompts:
            if prompt.is_valid:
                lines.append(json.dumps(prompt.to_training_format()))
        return "\n".join(lines)

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class GenerationStats(BaseModel):
    """Statistics about seed prompt generation."""
    total_generated: int = 0
    total_valid: int = 0
    total_invalid: int = 0
    by_tool: Dict[str, int] = Field(default_factory=dict)
    by_complexity: Dict[str, int] = Field(default_factory=dict)
    edge_case_count: int = 0
    average_quality_score: Optional[float] = None
    generation_duration_seconds: Optional[float] = None

    @property
    def valid_rate(self) -> float:
        """Percentage of valid prompts."""
        if self.total_generated == 0:
            return 0.0
        return self.total_valid / self.total_generated

    def update_from_batch(self, batch: SeedBatch) -> None:
        """Update stats from a batch."""
        self.total_generated += batch.total_count
        self.total_valid += batch.valid_count
        self.total_invalid += (batch.total_count - batch.valid_count)

        for tool, count in batch.tool_distribution.items():
            self.by_tool[tool] = self.by_tool.get(tool, 0) + count

        for complexity, count in batch.complexity_distribution.items():
            self.by_complexity[complexity] = self.by_complexity.get(complexity, 0) + count

        self.edge_case_count += len(batch.get_edge_cases())

        # Update average quality score
        valid_prompts = batch.get_valid_prompts()
        scores = [p.quality_score for p in valid_prompts if p.quality_score is not None]
        if scores:
            if self.average_quality_score is None:
                self.average_quality_score = sum(scores) / len(scores)
            else:
                # Running average
                total_scores = self.total_valid
                self.average_quality_score = (
                    (self.average_quality_score * (total_scores - len(scores)) + sum(scores))
                    / total_scores
                )
